justcoding121/Titanium-Web-Proxy

- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
I fixed two small bugs in SessionEventArgs.
> SessionEventArgs: A typo in an exception + wrong decompression method for zlib when reading the request headers.

- Titanium.Web.Proxy/Helpers/CertificateManager.cs
It was located from the current directory. This can result in a
FileNotFoundException when an application that uses Titanium-Web-Proxy
is launched from another path, the root certificate is not registered
and capturing is started . E.g.  c:\> test\test.exe
> Locate makecert.exe next to the assembly

- Titanium.Web.Proxy/Http/HttpWebClient.cs
When the first line read in the HTTP response is empty, read thenext line into httpResult.
Fixes bug where next line was read but httpResult was not updated
> Fix to handle empty first-line in HTTP Response

- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
This will make it possible to read the request in the response event. :)
> Only check for locked request if not read already.

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/Tcp/TcpRow.cs
- Titanium.Web.Proxy/Tcp/TcpTable.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
* ProxyRunning property is added to ProxyServer class.
* IP Helper API 'GetExtendedTcpTable' method and relevant structures are wrapped.
* ProcessId property is added to HttpWebClient class.
> IP Helper API wrapped to associate port with process id

- Titanium.Web.Proxy/Exceptions/BodyNotFoundException.cs
- Titanium.Web.Proxy/Exceptions/ProxyAuthorizationException.cs
- Titanium.Web.Proxy/Exceptions/ProxyException.cs
- Titanium.Web.Proxy/Exceptions/ProxyHttpException.cs
- Titanium.Web.Proxy/ProxyAuthorizationHandler.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/ResponseHandler.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
Hi,
I found that, when there is exception when creating connection, there is no direct way for this `ProxyServer` class to know if a request is ever successful. When I look at the `ExceptionFunc` caller, there is no additional context provided, other than original thrown exception.
Therefore, I created a few custom exceptions, such has `ProxyHttpException`, that will contain additional context, `SessionEventArgs`, just like the same thing available to `BeforeRequest` and `BeforeResponse` event.
With this minor changes, `ProxyServer` caller that define `ExceptionFunc` will have additional context information about exception triggered. For example, now, caller could track if a request fails, then, plan to come out with appropriate response - this is something we work more on the future to …
> Proxy exception

- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
Doneness:
Allows binding the proxy to a specific network adapter.
proxyServer.LocalEndPoint = new IPEndPoint(IPAddress.Parse("192.168.1.2"), 0);
> Bind proxy requests to specific network adapter

- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnection.cs
- Titanium.Web.Proxy/Network/Tcp/TcpRow.cs
Minor modifications made to XML syntax to reduce warnings generated during compile.
This is my first code change contribution to a public open source project on GitHub.
As you will note, it modifies some XML statements in various files to be syntactically correct.  The only effect of this modification is to reduce warnings during compile.  I figure this patch has minimum potential to upset the apple cart while I try to figure out how best to contribute something useful.
Doneness:
> Minor XML syntax modifications

- Titanium.Web.Proxy/Network/CertificateManager.cs
- Titanium.Web.Proxy/RequestHandler.cs
If you load an assembly dynamically, the Location property is string.Empty:
https://msdn.microsoft.com/en-us/library/system.reflection.assembly.location(v=vs.110).aspx
In the GetRootCertificate method the Path.GetDirectoryName was called with the assembly.Location parameter. If you call this method with an empty string it throws ArgumentException.
This pull request changes the logic which tries to find the root certificate file. If the executing assemlby is dynamically loaded, tries to get the Location of the Entry assembly. It should be a real file with valid Location.
This logic was used in 2 places, in GetRootCertificate and in CreateTrustedRootCertificate, so I moved it to a common private method.
Doneness:
> ArgumentException fix when proxy dll is loaded dynamically

- Tests/Titanium.Web.Proxy.UnitTests/CertificateManagerTests.cs
- Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.cs
- Titanium.Web.Proxy/ProxyServer.cs
I saw that you renamed the CertificateCacheManager, so I renamed the 
CreateCertificateCacheManager to CreateCertificateManager, too
Also noticed that you renamed my private const field to camelCase, I used PascalCase becasuse in the project there were two PascalCase constants in BCCertificateMaker, I renamed those to camelCase. (So now they are the same everywhere)
And swapped the modifier order in CertificateManagerTest
Doneness:
> Small fixes

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/Network/CertificateManager.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
I'd like to implement my own Root certificate storing mechanism as in #175
Since some days ago it was possible to set the RootCertificate from outside, but I'd like to use the existing certification maker classes. (Don't want to reimplement `WinCertificateMaker` or `BCCertificateMaker` in my own code)
So I changed the Certification provider to public, which has now 3 public methods:
```
public bool CreateTrustedRootCertificate(bool persistToFile = true)
public void TrustRootCertificate()
public void RemoveTrustedRootCertificates()
```
The default behavior is the same as before, it will store the certificate to rootCert.pfx.
I was also thinking on changing the `ICertificateMaker` and `CertificateManger.CertEngine` to public, too.
Maybe it would be useful.
`RemoveTrustedRootCertificates` …
> RootCertificate creation improvements

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/Extensions/TcpExtensions.cs
- Titanium.Web.Proxy/Helpers/CustomBinaryReader.cs
- Titanium.Web.Proxy/Helpers/CustomBufferedStream.cs
- Titanium.Web.Proxy/Helpers/Network.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HeaderParser.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Http/Request.cs
- Titanium.Web.Proxy/Models/HttpHeader.cs
- Titanium.Web.Proxy/Network/Tcp/TcpRow.cs
- Titanium.Web.Proxy/ProxyAuthorizationHandler.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/ResponseHandler.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- Use static Http Verion objects
- Common HTTP header parser (request, response)
- Code duplication removed from ProxyAuthorizationHandler
- Fix? for issue #227
Doneness:
> - Create less TcpRow objects

- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/Helpers/CustomBinaryReader.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/RequestHandler.cs
> reuse buffers, missing dispose added

- Titanium.Web.Proxy/Helpers/CustomBinaryReader.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/ResponseHandler.cs
> move Dispose calls to finally blocks

- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/ResponseHandler.cs
> add TLS cert revocation check flag; cleanup

- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
mono's old xbuild probably ignored this section, but mono's new msbuild tries to find AxImp.exe. This tool is not available on Linux:
> /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(2563,5): warning MSB3084: Task attempted to find "AxImp.exe" in two locations. 1) Under the "/usr/lib/mono/4.5/" processor specific directory which is generated based on SdkToolsPath 2) The x86 specific directory under "/usr/lib/mono/4.5/" which is specified by the SDKToolsPath property. You may be able to solve the problem by doing one of the following:  1) Set the "SDKToolsPath" property to the location of the Microsoft Windows SDK. [/home/user/DebSource/PLSProxy/Titanium.Web.Proxy/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj] …
> Added OS condition for referencing COM library

- Titanium.Web.Proxy/RequestHandler.cs
If args.WebSession.Request.CancelRequest, then GetServerConnection() shouldn't be called.  This fixes the following problems:
1.  If you don't, you'll still to the web-request.   So, in the case when you want to block something like "google.com", and return custom HTML that has text like "Blocked by titanium web proxy", if you set the connection, it will still do the web-request, which is unnecessary, and sometimes may be undesirable.
2.  If someone calls `await e.Ok()` to return custom data, they may want to so based on the absoluteurl containing a hostname that may not even resolve.   For instance "http://xyzxyz/...", and xyzxyz is not a valid hostname.   If you attempt a connection, the dns won't resolve, and the entire thing will be aborted.  This means, the data sent to  `await …
> On CancelRequest, bypass connection

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/EventArguments/TunnelConnectEventArgs.cs
- Titanium.Web.Proxy/Helpers/CustomBufferedStream.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/ConnectRequest.cs
- Titanium.Web.Proxy/Http/ConnectResponse.cs
- Titanium.Web.Proxy/Http/HeaderCollection.cs
- Titanium.Web.Proxy/Http/HeaderParser.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Http/HttpsTools.cs
- Titanium.Web.Proxy/Http/Request.cs
- Titanium.Web.Proxy/Http/Response.cs
- Titanium.Web.Proxy/Models/EndPoint.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnection.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyAuthorizationHandler.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/ResponseHandler.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- Titanium.Web.Proxy/WinAuthHandler.cs
- Using upstream proxy when host is excluded, too (earlier upstream proxy was ignored in this case which is wrong)
Doneness:
I tried to test it carefully with HTTP site, excluded HTTPS site and non excluded HTTPS site. With and without upstream proxy. It seems to work now in all cases. I hope there is no bug... or at least better then earlier:)
> Detect HTTPS ClientHello instead of manually listing the HTTPS ports +bugfix

- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
Doneness:
Very simple addition I made due to https://github.com/justcoding121/Titanium-Web-Proxy/issues/325
This allows one to target a request based on which endpoint received it.
> Expose the endpoint that the request came in via with SessionEventArgs

- Titanium.Web.Proxy/Http/ConnectResponse.cs
- Titanium.Web.Proxy/Http/KnownHeaders.cs
Fixes connection blocking issues on Android emulators caused by adding not-needed Timestamp HTTP Header set on the CONNECT response.
I've tested the fix on Android, Mac and iOS - no issues have been found.
Doneness:
> Fixes connection blocking issues on Android emulators

- Titanium.Web.Proxy/Models/ProxyAuthenticationContext.cs
- Titanium.Web.Proxy/ProxyAuthorizationHandler.cs
- Titanium.Web.Proxy/ProxyServer.cs
…for things like NTLM or Kerberos, instead of falling back to Basic.
This extends the original functionality by adding a delegate to check if an arbitrary scheme has been presented instead of just Basic. This includes the ability to use multi-trip handshakes like NTLM or Kerberos.
It's written such that it won't break any existing implementations using the original authentication path.
Doneness:
> Added ability to inject a custom authentication mechanism

- Titanium.Web.Proxy/Http/Response.cs
Fixing response status line parsing, so that status line is parsed correctly even if Reason-Phrase is missing. HTTP spec says the Reason-Phrase is optional.
Doneness:
> Fixing response status line parsing

- Titanium.Web.Proxy/Http/HttpWebClient.cs
> Fix environment specific header termination on Unix (issue #483)

- .vscode/settings.json
- omnisharp.json
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
- src/Titanium.Web.Proxy/RequestHandler.cs
- src/Titanium.Web.Proxy/TransparentClientHandler.cs
> Dns resolve from code

- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
> check session for null

- src/Titanium.Web.Proxy/Compression/CompressionFactory.cs
- src/Titanium.Web.Proxy/Compression/DecompressionFactory.cs
- src/Titanium.Web.Proxy/Http/KnownHeaders.cs
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
> Add brotli compression for windows

- examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- examples/Titanium.Web.Proxy.Examples.Basic/Titanium.Web.Proxy.Examples.Basic.csproj
- src/Titanium.Web.Proxy/Network/CertificateManager.cs
> Console lock issues

- src/Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.cs
> Fixes #509 (BCCertificateMaker issue on Mono)

- src/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- tests/Titanium.Web.Proxy.IntegrationTests/InterceptionTests.cs
- tests/Titanium.Web.Proxy.IntegrationTests/ProxyTestController.cs
- tests/Titanium.Web.Proxy.IntegrationTests/Titanium.Web.Proxy.IntegrationTests.csproj
> Read body and cancel request to server

- src/Titanium.Web.Proxy/RequestHandler.cs
- src/Titanium.Web.Proxy/ResponseHandler.cs
> refactor connection generation

- src/Titanium.Web.Proxy/Helpers/HttpWriter.cs
buffers were returned to the pool before the write operation finished, which lead to corrupted buffers
Doneness:
> fix buffers returned to pool too early

- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
Doneness:
By disabling NAGLE over TCP, network performances are approximatively 50% faster.
> Disable Nagle algorithm (really better network performances)

- src/Titanium.Web.Proxy/RequestHandler.cs
- tests/Titanium.Web.Proxy.IntegrationTests/HttpsTests.cs
Doneness:
- [X ] Build is okay - I made sure that this change is building successfully.
> Fix fake tunnel failure

- src/Titanium.Web.Proxy/ProxyServer.cs
Doneness:
- [X ] Build is okay - I made sure that this change is building successfully.
- [ X] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [ X] Branching - If this is not a hotfix, I am making this request against the master branch 
Tasks use ThreadPool. 
By default there is only few threads available (approx 20), and if you start the proxy and open a heavy website with hundred requests (like www.lemonde.fr) it could hang for approx 20sec (because of the task scheduler), and then continue. 
On possibility is to rewrite Titanium without async/await... 
And the other - and probably the best - is to tune ThreadPool.MinThreadWorker based on the connections opening/close, it works really better with that (have a try …
> Add ThreadPool tuning for better performances when heavy load

- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
Doneness:
- [ X] Build is okay - I made sure that this change is building successfully.
- [ X] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [ X] Branching - If this is not a hotfix, I am making this request against the master branch 
On server connection - when you download/upload on the Internet - it's really faster to send/receive data with the default 64k buffer. If you try to change the SendTimeout/ReceiveTimeout socket values, it will have worst performances.
> Don't change the Server Socket SendBufferSize or ReceiveBufferSize

- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
Doneness:
Remove the ThreadPool optimization stuff, useless now with the bug fix for Stream-Extended (https://github.com/justcoding121/Stream-Extended/pull/44).
I add a new setting param "ThreadPoolWorkerThread" for tuning the ThreadPool once instead (usefull for servers)
Example:
proxyServer.ThreadPoolWorkerThread = Environment.ProcessorCount * 6;
> Remove ThreadPool auto optimizations, add a manual ThreadPoolWorkerThread

- src/Titanium.Web.Proxy/ExplicitClientHandler.cs
- src/Titanium.Web.Proxy/Http2/Http2Helper.cs
- src/Titanium.Web.Proxy/Models/ExplicitProxyEndPoint.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.NetCore.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
> prepare for basic http/2 support and another small fixes (typo, version numbers)

- examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- src/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- src/Titanium.Web.Proxy/EventArguments/SessionEventArgsBase.cs
- src/Titanium.Web.Proxy/Http/RequestResponseBase.cs
- src/Titanium.Web.Proxy/Http2/Http2Helper.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpClientConnection.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
> HTTP/2: allow to read the body

- examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml
- examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- examples/Titanium.Web.Proxy.Examples.Wpf/ObservableCollectionEx.cs
- examples/Titanium.Web.Proxy.Examples.Wpf/Titanium.Web.Proxy.Examples.Wpf.csproj
- src/StreamExtended/Network/CustomBufferedStream.cs
- src/Titanium.Web.Proxy/EventArguments/LimitedStream.cs
- src/Titanium.Web.Proxy/ExplicitClientHandler.cs
- src/Titanium.Web.Proxy/Helpers/HttpRequestWriter.cs
- src/Titanium.Web.Proxy/Http/HttpWebClient.cs
- src/Titanium.Web.Proxy/Http/Request.cs
- src/Titanium.Web.Proxy/Http2/Http2Helper.cs
- src/Titanium.Web.Proxy/ResponseHandler.cs
- tests/Titanium.Web.Proxy.IntegrationTests/Helpers/HttpContinueClient.cs
- tests/Titanium.Web.Proxy.IntegrationTests/Helpers/HttpMessageParsing.cs
> Small HTTP/2 and other improvements

- src/StreamExtended/Network/CopyStream.cs
- src/StreamExtended/Network/CustomBufferedStream.cs
- src/StreamExtended/StreamExtended.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.Mono.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.NetCore.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
- tests/Titanium.Web.Proxy.IntegrationTests/Titanium.Web.Proxy.IntegrationTests.csproj
- tests/Titanium.Web.Proxy.UnitTests/Titanium.Web.Proxy.UnitTests.csproj
> nuget package consolidation

- examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- src/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- src/Titanium.Web.Proxy/Http/RequestResponseBase.cs
- src/Titanium.Web.Proxy/Http2/Hpack/Encoder.cs
- src/Titanium.Web.Proxy/Http2/Hpack/StaticTable.cs
- src/Titanium.Web.Proxy/Http2/Http2FrameFlag.cs
- src/Titanium.Web.Proxy/Http2/Http2FrameHeader.cs
- src/Titanium.Web.Proxy/Http2/Http2FrameType.cs
- src/Titanium.Web.Proxy/Http2/Http2Helper.cs
- src/Titanium.Web.Proxy/Models/HttpHeader.cs
- src/Titanium.Web.Proxy/ResponseHandler.cs
Doneness:
known issues: 
- some http/2 validation is not enforced
- generated header is always 1 frame (can be bigger than a valid frame size), however I never saw any splitted header, yet
- copyHttp2FrameAsync method looks ugly, especially the encoding part, long
> allow to modify HTTP/2 header

- examples/Titanium.Web.Proxy.Examples.Basic/Titanium.Web.Proxy.Examples.Basic.NetCore.csproj
- examples/Titanium.Web.Proxy.Examples.Basic/Titanium.Web.Proxy.Examples.Basic.csproj
- examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- examples/Titanium.Web.Proxy.Examples.Wpf/Properties/Resources.Designer.cs
- examples/Titanium.Web.Proxy.Examples.Wpf/Properties/Settings.Designer.cs
- examples/Titanium.Web.Proxy.Examples.Wpf/Titanium.Web.Proxy.Examples.Wpf.NetCore.csproj
- examples/Titanium.Web.Proxy.Examples.Wpf/Titanium.Web.Proxy.Examples.Wpf.csproj
- src/Titanium.Web.Proxy.sln
- src/Titanium.Web.Proxy/StreamExtended/Network/CustomBufferedStream.cs
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.NetCore.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
> Master to beta

- src/Titanium.Web.Proxy/Extensions/UriExtensions.cs
- src/Titanium.Web.Proxy/Http/HttpWebClient.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
> Fix for #593 and #596

- src/Titanium.Web.Proxy/EventArguments/SessionEventArgsBase.cs
- src/Titanium.Web.Proxy/RequestHandler.cs
- src/Titanium.Web.Proxy/ResponseHandler.cs
> Support EnableWinAuth per session #633

- src/Titanium.Web.Proxy/Helpers/HttpHelper.cs
- src/Titanium.Web.Proxy/StreamExtended/Network/CustomBufferedStream.cs
> Another fix for  #638

- examples/Titanium.Web.Proxy.Examples.Basic/Titanium.Web.Proxy.Examples.Basic.csproj
- src/Titanium.Web.Proxy/ExplicitClientHandler.cs
- src/Titanium.Web.Proxy/Extensions/SslExtensions.cs
- src/Titanium.Web.Proxy/Helpers/HttpHelper.cs
- src/Titanium.Web.Proxy/Http2/Http2Helper.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpClientConnection.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpServerConnection.cs
- src/Titanium.Web.Proxy/RequestHandler.cs
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
- tests/Titanium.Web.Proxy.IntegrationTests/ExpectContinueTests.cs
- tests/Titanium.Web.Proxy.IntegrationTests/Helpers/HttpContinueClient.cs
- tests/Titanium.Web.Proxy.IntegrationTests/Helpers/HttpContinueServer.cs
- tests/Titanium.Web.Proxy.IntegrationTests/Helpers/HttpMessageParsing.cs
- tests/Titanium.Web.Proxy.IntegrationTests/NestedProxyTests.cs
- tests/Titanium.Web.Proxy.IntegrationTests/ReverseProxyTests.cs
- tests/Titanium.Web.Proxy.IntegrationTests/Titanium.Web.Proxy.IntegrationTests.csproj
> netcoreapp2.1 target removed, use netstandard 2.1

- src/Titanium.Web.Proxy/Helpers/RunTime.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
Adds RunTime.IsSocketReuseAvailable and adds the ability to use socket reuse outside of windows depending on the framework version. (Bug that was causing issues has been fixed in core 3.0+).
Doneness:
> Enable socket reuse based on framework

- src/Titanium.Web.Proxy/EventArguments/SessionEventArgsBase.cs
> fixed "Windows Authentication is not supported" error on non-Windows systems

- src/Titanium.Web.Proxy/Models/TransparentProxyEndPoint.cs
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
> missing dependencies added

- src/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- src/Titanium.Web.Proxy/Http2/Http2Helper.cs
> fix for #652

- src/Titanium.Web.Proxy/EventArguments/SessionEventArgsBase.cs
- src/Titanium.Web.Proxy/Helpers/WinHttp/WinHttpWebProxyFinder.cs
- src/Titanium.Web.Proxy/Models/ExternalProxy.cs
- src/Titanium.Web.Proxy/Models/IExternalProxy.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpServerConnection.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
- tests/Titanium.Web.Proxy.IntegrationTests/NestedProxyTests.cs
Changes ExternalProxy params to IExternalProxy so a custom class can be used when needed and makes ExternalProxy use IExternalProxy. ExternalProxy is still used as a default class internally.
Doneness:
> ExternalProxy interface

- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
If establishing a connection takes longer than ConnectTimeOutSeconds it will try the next address or fail the connect instead of waiting for the default timeout which is usually 20-30 seconds. Most users will want to change this to something reasonable like 6-10 seconds but to stick with normal operation the default is set to 20 seconds.
Doneness:
> Add support for connect timeout

- examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
Adds ability to handle upstream proxy connect failures by using a new upstream proxy if the user provides one. I'm not sure if this is how you would do this @honfika so lmk...
closes #646 
Doneness:
> Adds ability to handle upstream proxy connect failures

- src/Titanium.Web.Proxy/ExplicitClientHandler.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/RequestHandler.cs
- src/Titanium.Web.Proxy/TransparentClientHandler.cs
> Another websocket fix

- examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- src/Titanium.Web.Proxy/ExplicitClientHandler.cs
- src/Titanium.Web.Proxy/Helpers/HttpStream.cs
- src/Titanium.Web.Proxy/Helpers/NullWriter.cs
- src/Titanium.Web.Proxy/Net45Compatibility.cs
> less exceptions

- src/Titanium.Web.Proxy/Http/HttpWebClient.cs
- src/Titanium.Web.Proxy/Http/Response.cs
> No body for head request (#695)

- examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- src/Titanium.Web.Proxy/Http2/Http2Helper.cs
- src/Titanium.Web.Proxy/Models/SocksProxyEndPoint.cs
- src/Titanium.Web.Proxy/Models/TransparentBaseProxyEndPoint.cs
- src/Titanium.Web.Proxy/Net45Compatibility.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpClientConnection.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpServerConnection.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
- src/Titanium.Web.Proxy/ProxySocket/SocksHandler.cs
- src/Titanium.Web.Proxy/RequestHandler.cs
- src/Titanium.Web.Proxy/ResponseHandler.cs
- src/Titanium.Web.Proxy/SocksClientHandler.cs
- src/Titanium.Web.Proxy/TransparentClientHandler.cs
> socks endpoint

- src/Titanium.Web.Proxy/Helpers/Net45Compatibility.cs
awaiting `new Task(() => { })` never finishes since the task is never started
Doneness:
> .Net45 compatibility returns a finished task

- src/Titanium.Web.Proxy/TransparentClientHandler.cs
Doneness:
- [ x] Build is okay - I made sure that this change is building successfully.
- [x ] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [ x] Branching - If this is not a hotfix, I am making this request against the master branch 
I found that using Titanium as a reverse proxy doesn't work with HTTPS unless you update the TLS version to 1.2 because most browsers are not accepting the older version used as default.
> Update the TLS version used in TransparentClientHandler.cs
