- Titanium.Web.Proxy/Helpers/CertificateManager.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
* Thread-safe
* Certificate caching
* Create customly named self-signed certificate(s).
* Remove generated certificates.
> New class to handle certificates.

- Titanium.Web.Proxy/Models/SessionEventArgs.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/ResponseHandler.cs
Make this fully asynchronous. Fix request modification
> Use Async for each session

- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
Fixed an issue I found where the string.Format parameters were incorrect.
> Fixed issue where string.Format parameters were not in sequence

- .build/default.ps1
- README.md
- Titanium.Web.Proxy/ResponseHandler.cs
* Properly dispose TcpClient to avoid browser trying to reuse dead connections
> Fix performance degradation

- Titanium.Web.Proxy/ProxyServer.cs
Just a tiny little typo, but confused me when testing :-)
> Fixed console message typo in SetAsSystemHttpProxy

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/CertificateHandler.cs
- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/Extensions/HttpWebRequestExtensions.cs
- Titanium.Web.Proxy/Extensions/HttpWebResponseExtensions.cs
- Titanium.Web.Proxy/Extensions/StreamExtensions.cs
- Titanium.Web.Proxy/Extensions/TcpExtensions.cs
- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Http/Request.cs
- Titanium.Web.Proxy/Http/Response.cs
- Titanium.Web.Proxy/Models/HttpHeader.cs
- Titanium.Web.Proxy/Network/CertificateManager.cs
- Titanium.Web.Proxy/Network/TcpConnectionCacheManager.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/ResponseHandler.cs
#87 Addressed second item on checklist.
> Perf improve

- Titanium.Web.Proxy/Network/TcpConnection.cs
- Titanium.Web.Proxy/Network/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/ResponseHandler.cs
Set NoDelay to false so as to enable default Tcp Naggle algorithm
> enable Nagle algorithm

- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/ProxyServer.cs
Added another constructor to the ProxyServer to allow the root certificate name and issuer to be set
Added support for custom headers to SessionEventArgs.Ok() method
> Root Cert Name, Headers support for SessionEventArgs.Ok()

- Tests/Titanium.Web.Proxy.UnitTests/ProxyServerTests.cs
- Tests/Titanium.Web.Proxy.UnitTests/Titanium.Web.Proxy.UnitTests.csproj
- Titanium.Web.Proxy/ProxyServer.cs
Doneness:
- [x ] Build is okay - I made sure that this change is building successfully.
- [ x] No Bugs - I made sure that this change is working properly as expected. It does'nt have any bugs that you are aware of. 
- [x ] Branching - If this is not a hotfix, I am making this request against release branch (aka beta branch)
Also fixed a compare-by-reference-bug
> Added support for multiple zero-port end points for the same address

- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Models/EndPoint.cs
- Titanium.Web.Proxy/Models/ExternalProxy.cs
- Titanium.Web.Proxy/Network/TcpConnection.cs
- Titanium.Web.Proxy/Network/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/Tcp/TcpRow.cs
ProcessId on WebSession is fixed to get the correct pid.
> ProcessId is fixed on HttpWebClient

- appveyor.yml
> update build number

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- README.md
- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/RequestHandler.cs
Doneness:
Add support for request with PATCH method - treat it similar to POST and PUT method. PATCH method is similar to PUT method, but semantically it is different as it allows update on part of the item. In my enterprise setting use case, we do have quite a number of Web API with PATCH method.
FYI. Note that, all unit test passed, except the unit test re Certificate (as it is already failed before this changes).
> Add support for request with PATCH method

- Titanium.Web.Proxy/Network/TcpConnectionFactory.cs
- Titanium.Web.Proxy/RequestHandler.cs
> Manually setting StreamWriter's NewLine to \r\n to fix HTTP header on Linux

- PULL_REQUEST_TEMPLATE.md
- README.md
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- appveyor.yml
Doneness:
- [x ] Build is okay - I made sure that this change is building successfully.
- [ x] No Bugs - I made sure that this change is working properly as expected. It does'nt have any bugs that you are aware of. 
- [x ] Branching - If this is not a hotfix, I am making this request against develop branch
> Beta release

- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/Http/Responses/GenericResponse.cs
Doneness:
- [X ] Build is okay - I made sure that this change is building successfully.
> Adding generic response creation

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- README.md
- Titanium.Web.Proxy/Models/EndPoint.cs
- Titanium.Web.Proxy/RequestHandler.cs
Enhancement https://github.com/justcoding121/Titanium-Web-Proxy/issues/79
Doneness:
- [x ] Build is okay - I made sure that this change is building successfully.
- [x ] No Bugs - I made sure that this change is working properly as expected. It does'nt have any bugs that you are aware of. 
- [x ] Branching - If this is not a hotfix, I am making this request against develop branch
> Added option to use generic certificate with explicit endpoint

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- README.md
- Titanium.Web.Proxy/ProxyServer.cs
> Merge Beta with develop

- Titanium.Web.Proxy/ProxyServer.cs
Fix exception func passed as null
Doneness:
> #196 Merge bugfix in develop with beta

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.cs
- Titanium.Web.Proxy/Network/Certificate/WinCertificateMaker.cs
Fix Certificate Maker for Windows to support alt names
Doneness:
> #180 #199 Fixed windows certificate maker to support alternative names.

- Titanium.Web.Proxy/Network/Certificate/WinCertificateMaker.cs
cleanup win cert maker
Doneness:
> optimize certificate maker for alternative subject names

- Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.cs
> #199 Fix subject alt names for Bouncy Castle

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/Models/EndPoint.cs
- Titanium.Web.Proxy/Network/CertificateManager.cs
- Titanium.Web.Proxy/ProxyAuthorizationHandler.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
> #205 IncludedHttpsHostNameRegex  and #207 Inconsistent naming fixes

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- README.md
- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Models/EndPoint.cs
- Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.cs
- Titanium.Web.Proxy/Network/Certificate/WinCertificateMaker.cs
- Titanium.Web.Proxy/Network/CertificateManager.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnection.cs
- Titanium.Web.Proxy/Network/Tcp/TcpRow.cs
- Titanium.Web.Proxy/ProxyAuthorizationHandler.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
> Beta release 

- Titanium.Web.Proxy/Extensions/HttpWebRequestExtensions.cs
- Titanium.Web.Proxy/Extensions/HttpWebResponseExtensions.cs
- Titanium.Web.Proxy/Extensions/StringExtensions.cs
- Titanium.Web.Proxy/Helpers/CustomBinaryReader.cs
- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Http/Request.cs
- Titanium.Web.Proxy/Http/Response.cs
- Titanium.Web.Proxy/Models/EndPoint.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyAuthorizationHandler.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- reduced the number of the created byte[] (including the arrays created inside MemoryStream)
- use compiled regexes
- some string concatenation changed
- ToLower + "==" changed to ignore case comparision
Doneness:
> Performance improvements:

- README.md
- Tests/Titanium.Web.Proxy.UnitTests/Titanium.Web.Proxy.UnitTests.csproj
- Tests/Titanium.Web.Proxy.UnitTests/WinAuthTests.cs
- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/Helpers/RunTime.cs
- Titanium.Web.Proxy/Network/WinAuth/Security/BufferWrapper.cs
- Titanium.Web.Proxy/Network/WinAuth/Security/Common.cs
- Titanium.Web.Proxy/Network/WinAuth/Security/EndPoint.cs
- Titanium.Web.Proxy/Network/WinAuth/Security/LittleEndian.cs
- Titanium.Web.Proxy/Network/WinAuth/Security/Message.cs
- Titanium.Web.Proxy/Network/WinAuth/Security/State.cs
- Titanium.Web.Proxy/Network/WinAuth/Security/WinAuthEndPoint.cs
- Titanium.Web.Proxy/Network/WinAuth/WinAuthHandler.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/ResponseHandler.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- Titanium.Web.Proxy/WinAuthHandler.cs
> ntlm kerberos

- Titanium.Web.Proxy/Helpers/CustomBinaryReader.cs
- Titanium.Web.Proxy/Helpers/CustomBufferedStream.cs
- Titanium.Web.Proxy/Network/CertificateManager.cs
> Buffered stream improvements, allow to remove the machine root certificate as administrator

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/Helpers/CustomBinaryReader.cs
- Titanium.Web.Proxy/Helpers/CustomBufferedStream.cs
- Titanium.Web.Proxy/ProxyServer.cs
> Push dispose fix on buffered stream to beta

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
> Push dispose fix on buffered stream to stable

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/ProxyServer.cs
> Configure system proxy in one step #256

- Examples/Titanium.Web.Proxy.Examples.Basic/Program.cs
- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/ProxyServer.cs
> Restore proxy settings on proxy stop/exit

- Titanium.Web.Proxy/Helpers/SystemProxy.cs
> Save and clear AutoConfigURL registry value when enable system proxy

- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
> Typo. Linux hates that lower case C :-)

- Titanium.Web.Proxy/ProxyServer.cs
> Using WebRequest to retrieve upstream proxy

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Tests/Titanium.Web.Proxy.UnitTests/SystemProxyTest.cs
- Tests/Titanium.Web.Proxy.UnitTests/Titanium.Web.Proxy.UnitTests.csproj
- Titanium.Web.Proxy/Helpers/ProxyInfo.cs
- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/Helpers/WinHttp/NativeMethods.WinHttp.cs
- Titanium.Web.Proxy/Helpers/WinHttp/WinHttpHandle.cs
- Titanium.Web.Proxy/Helpers/WinHttp/WinHttpWebProxyFinder.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
> #264 GetSystemUpStreamProxy fixed

- Tests/Titanium.Web.Proxy.UnitTests/SystemProxyTest.cs
- Titanium.Web.Proxy/Helpers/ProxyInfo.cs
- Titanium.Web.Proxy/Helpers/SystemProxy.cs
- Titanium.Web.Proxy/Helpers/WinHttp/WinHttpWebProxyFinder.cs
- Titanium.Web.Proxy/ProxyServer.cs
> Bypass list implemented + tests

- Examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml
- Examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- Examples/Titanium.Web.Proxy.Examples.Wpf/SessionListItem.cs
- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HeaderCollection.cs
- Titanium.Web.Proxy/Http/Request.cs
- Titanium.Web.Proxy/Http/Response.cs
- Titanium.Web.Proxy/Models/HttpHeader.cs
- Titanium.Web.Proxy/RequestHandler.cs
> Fixes and Demo app improvements

- Examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/RequestHandler.cs
> Fix for #284

- Examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- Examples/Titanium.Web.Proxy.Examples.Wpf/SessionListItem.cs
- Titanium.Web.Proxy/Helpers/CustomBufferedPeekStream.cs
- Titanium.Web.Proxy/Helpers/CustomBufferedStream.cs
- Titanium.Web.Proxy/Http/ConnectRequest.cs
- Titanium.Web.Proxy/Http/ConnectResponse.cs
- Titanium.Web.Proxy/Http/HeaderCollection.cs
- Titanium.Web.Proxy/Http/HttpsTools.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
> Parse Ssl client hello

- Titanium.Web.Proxy/Helpers/CustomBufferedPeekStream.cs
- Titanium.Web.Proxy/Http/ConnectRequest.cs
- Titanium.Web.Proxy/Http/HttpsTools.cs
> Parse ssl extensions

- Examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Http/Request.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnection.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/RequestHandler.cs
Doneness:
I tried it with no upstream proxy, with local upstream proxy without authentication, and a remote proxy with authentication. They seems to work.
> Fix for #289

- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/RequestHandler.cs
> Fix for fix for #289:)

- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnection.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/Ssl/ClientHelloInfo.cs
- Titanium.Web.Proxy/Ssl/ServerHelloInfo.cs
- Titanium.Web.Proxy/Ssl/SslTools.cs
> Parse server hello + minor impovements

- Titanium.Web.Proxy/Helpers/CustomBufferedPeekStream.cs
- Titanium.Web.Proxy/Network/Tcp/ClientHelloAlpnAdderStream.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/Ssl/ClientHelloInfo.cs
- Titanium.Web.Proxy/Ssl/SslTools.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
> Add ALPN Ssl extension

- Titanium.Web.Proxy/Network/Tcp/ServerHelloAlpnAdderStream.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/Ssl/ServerHelloInfo.cs
- Titanium.Web.Proxy/Ssl/SslTools.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
> Add ALPN ssl extension to server hello

- Examples/Titanium.Web.Proxy.Examples.Basic.Standard/Helpers/ConsoleHelper.cs
- Examples/Titanium.Web.Proxy.Examples.Basic.Standard/Program.cs
- Examples/Titanium.Web.Proxy.Examples.Basic.Standard/ProxyTestController.cs
- Examples/Titanium.Web.Proxy.Examples.Basic.Standard/Titanium.Web.Proxy.Examples.Basic.Standard.csproj
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/Titanium.Web.Proxy.Standard.csproj
> .NET standard improvement + .NET core test project

- appveyor.yml
> remove account/private feeds

- Titanium.Web.Proxy/ProxyServer.cs
> netstandard2 proxy start fix

- Titanium.Web.Proxy/Network/Certificate/BCCertificateMaker.cs
- Titanium.Web.Proxy/Network/Certificate/WinCertificateMaker.cs
> add timeout to WinCert maker, too. Try-catch added

- Titanium.Web.Proxy/RequestHandler.cs
> Proxy authentication should be checked for excluded sites, too

- Examples/Titanium.Web.Proxy.Examples.Basic/ProxyTestController.cs
- Titanium.Web.Proxy/Models/EndPoint.cs
- Titanium.Web.Proxy/ProxyServer.cs
> Include exception data when listener faield to start

- Titanium.Web.Proxy/ProxyServer.cs
Doneness:
- [ X] Build is okay - I made sure that this change is building successfully.
- [ X] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [ X] Branching - If this is not a hotfix, I am making this request against develop branch
> Update IsSystemHttpProxy condition

- Titanium.Web.Proxy/RequestHandler.cs
> Request Url fix

- Titanium.Web.Proxy/Extensions/StringExtensions.cs
- Titanium.Web.Proxy/Helpers/HttpHelper.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
- Titanium.Web.Proxy/Http/HeaderCollection.cs
- Titanium.Web.Proxy/Http/HeaderParser.cs
- Titanium.Web.Proxy/Http/HttpWebClient.cs
- Titanium.Web.Proxy/Http/KnownHeaders.cs
- Titanium.Web.Proxy/Http/Request.cs
- Titanium.Web.Proxy/Http/Response.cs
- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/ProxyAuthorizationHandler.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/WinAuthHandler.cs
> beta | develop

- Titanium.Web.Proxy/Http/Request.cs
> merge develop to beta before merging PR #371

- Examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- Titanium.Web.Proxy/ProxyServer.cs
Doneness:
- [*] Build is okay - I made sure that this change is building successfully.
- [*] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of.
> Fix & Add property TrustRootCertificateAsAdministrator 

- Examples/Titanium.Web.Proxy.Examples.Wpf/MainWindow.xaml.cs
- Titanium.Web.Proxy/EventArguments/LimitedStream.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
> merge to beta

- Titanium.Web.Proxy/ResponseHandler.cs
- Titanium.Web.Proxy/WinAuthHandler.cs
Doneness:
PR resolves #394 and also fixes a recently introduced issue with body consumption for responses during ReRequests.
> Win auth concurrency fix

- Titanium.Web.Proxy/Network/WinAuth/Security/State.cs
- Titanium.Web.Proxy/Network/WinAuth/Security/WinAuthEndPoint.cs
- Titanium.Web.Proxy/ResponseHandler.cs
- Titanium.Web.Proxy/WinAuthHandler.cs
> State handling of WinAuth, fixes issue with failed authentication

- Titanium.Web.Proxy/RequestHandler.cs
> Transparent endpoint HTTP CONNECT handling is broken #339

- Titanium.Web.Proxy/Http/ConnectResponse.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/WinAuthHandler.cs
> Http 1.0 ConnectResponse and WinAuth request body fix

- Titanium.Web.Proxy/Helpers/Tcp.cs
> Fix releasing memory in GetProcessIdByLocalPort

- Titanium.Web.Proxy/Helpers/NativeMethods.Tcp.cs
- Titanium.Web.Proxy/Helpers/Tcp.cs
I get process id for every proxy connection, so this function is bottleneck for me :)
> Additonal optimizations in GetProcessIdByLocalPort

- Titanium.Web.Proxy/Network/CertificateManager.cs
- Titanium.Web.Proxy/ProxyServer.cs
> propagate ExceptionFunc to CertificateManager

- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- Titanium.Web.Proxy/RequestHandler.cs
Doneness:
- [x ] Build is okay - I made sure that this change is building successfully.
- [x ] Branching - If this is not a hotfix, I am making this request against develop branch
> remove version & connect from cache key

- Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
Doneness:
- [X ] Build is okay - I made sure that this change is building successfully.
- [X ] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [X ] Branching - If this is not a hotfix, I am making this request against develop branch
> Cache improvements

- Titanium.Web.Proxy/ExplicitClientHandler.cs
- Titanium.Web.Proxy/ProxyServer.cs
- Titanium.Web.Proxy/RequestHandler.cs
- Titanium.Web.Proxy/TransparentClientHandler.cs
> Fix prefetch connection leak

- Examples/Titanium.Web.Proxy.Examples.Wpf/Titanium.Web.Proxy.Examples.Wpf.csproj
- Examples/Titanium.Web.Proxy.Examples.Wpf/packages.config
- Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
- Titanium.Web.Proxy/packages.config
Doneness:
- [X ] No Bugs - I made sure that this change is working properly as expected. It doesn't have any bugs that you are aware of. 
- [X ] Branching - If this is not a hotfix, I am making this request against develop branch
> update StreamExtended package to stable

- Titanium.Web.Proxy/Network/RetryPolicy.cs
- Titanium.Web.Proxy/RequestHandler.cs
> retry without polly fixes

- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
> use correct nuget package name as dependency

- src/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
> use orginal lib now strongly named

- examples/Titanium.Web.Proxy.Examples.Wpf/Titanium.Web.Proxy.Examples.Wpf.csproj
- examples/Titanium.Web.Proxy.Examples.Wpf/packages.config
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.Mono.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.NetCore.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
> Update stream extended

- src/Titanium.Web.Proxy/Helpers/RunTime.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/ProxyServer.cs
Reverts justcoding121/Titanium-Web-Proxy#647
> Reverts justcoding121/Titanium-Web-Proxy#647

- src/Titanium.Web.Proxy/EventArguments/SessionEventArgs.cs
- src/Titanium.Web.Proxy/Helpers/RunTime.cs
- src/Titanium.Web.Proxy/Http/HeaderBuilder.cs
- src/Titanium.Web.Proxy/Http2/Hpack/Decoder.cs
- src/Titanium.Web.Proxy/Http2/Hpack/DynamicTable.cs
- src/Titanium.Web.Proxy/Net45Compatibility.cs
- src/Titanium.Web.Proxy/Network/Tcp/TcpConnectionFactory.cs
- src/Titanium.Web.Proxy/RequestHandler.cs
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.csproj
- src/Titanium.Web.Proxy/Titanium.Web.Proxy.nuspec
> net4.5 support is back
